from Drizzle.Runtime import *## Behavior script: effectsEditorStart#class effectsEditorStart(LingoBehaviorScript):     def __init__(self):         super().__init__()            def exitframe(self):         spr = None        q = None        c = None        gdirectionkeys = None        l = None        _global._movie.exitlock = LingoGlobal.TRUE        _global.sprite(LingoNumber(243)).color = _global.color(LingoNumber(255),LingoNumber(255),LingoNumber(255))        _global.member("effectsMatrix").image = _global.image(LingoNumber(52),LingoNumber(40),LingoNumber(32))        _global.sprite(LingoNumber(212)).blend = LingoNumber(30)        _global.sprite(LingoNumber(213)).blend = LingoNumber(50)        _global.sprite(LingoNumber(214)).blend = LingoNumber(70)        _global.sprite(LingoNumber(215)).blend = LingoNumber(100)        for tmp_spr in LingoGlobal.pyrange(LingoNumber(3), LingoNumber(9)):             spr = tmp_spr            _global.sprite(spr).rect = LingoGlobal.rect(LingoNumber(16),LingoNumber(16),LingoGlobal.op_mul(LingoNumber(53),LingoNumber(16)),LingoGlobal.op_mul(LingoNumber(41),LingoNumber(16)))            tmp_spr = spr                    for tmp_q in LingoGlobal.pyrange(LingoNumber(1), _movieScript.gLOprops.size.loch):             q = tmp_q            for tmp_c in LingoGlobal.pyrange(LingoNumber(1), _movieScript.gLOprops.size.locv):                 c = tmp_c                _global.member("effectsMatrix").image.setpixel(LingoGlobal.op_sub(q,LingoNumber(1)),LingoGlobal.op_sub(c,LingoNumber(1)),_global.color(LingoNumber(0),LingoNumber(0),LingoNumber(0)))
                tmp_c = c                            tmp_q = q                    _global.member("TEimg1").image = _global.image(LingoGlobal.op_mul(LingoNumber(52),LingoNumber(16)),LingoGlobal.op_mul(LingoNumber(40),LingoNumber(16)),LingoNumber(16))        _global.member("TEimg2").image = _global.image(LingoGlobal.op_mul(LingoNumber(52),LingoNumber(16)),LingoGlobal.op_mul(LingoNumber(40),LingoNumber(16)),LingoNumber(16))        _global.member("TEimg3").image = _global.image(LingoGlobal.op_mul(LingoNumber(52),LingoNumber(16)),LingoGlobal.op_mul(LingoNumber(40),LingoNumber(16)),LingoNumber(16))        _global.member("levelEditImage1").image = _global.image(LingoGlobal.op_mul(LingoNumber(52),LingoNumber(16)),LingoGlobal.op_mul(LingoNumber(40),LingoNumber(16)),LingoNumber(16))        _global.member("levelEditImage2").image = _global.image(LingoGlobal.op_mul(LingoNumber(52),LingoNumber(16)),LingoGlobal.op_mul(LingoNumber(40),LingoNumber(16)),LingoNumber(16))        _global.member("levelEditImage3").image = _global.image(LingoGlobal.op_mul(LingoNumber(52),LingoNumber(16)),LingoGlobal.op_mul(LingoNumber(40),LingoNumber(16)),LingoNumber(16))        _global.member("levelEditImageShortCuts").image = _global.image(LingoGlobal.op_mul(LingoNumber(52),LingoNumber(16)),LingoGlobal.op_mul(LingoNumber(40),LingoNumber(16)),LingoNumber(16))        _movieScript.tedraw(LingoGlobal.rect(LingoNumber(1),LingoNumber(1),_movieScript.gLOprops.size.loch,_movieScript.gLOprops.size.locv),LingoNumber(1))
        _movieScript.tedraw(LingoGlobal.rect(LingoNumber(1),LingoNumber(1),_movieScript.gLOprops.size.loch,_movieScript.gLOprops.size.locv),LingoNumber(2))
        _movieScript.tedraw(LingoGlobal.rect(LingoNumber(1),LingoNumber(1),_movieScript.gLOprops.size.loch,_movieScript.gLOprops.size.locv),LingoNumber(3))
        _movieScript.lvleditdraw(LingoGlobal.rect(LingoNumber(1),LingoNumber(1),_movieScript.gLOprops.size.loch,_movieScript.gLOprops.size.locv),LingoNumber(1))
        _movieScript.lvleditdraw(LingoGlobal.rect(LingoNumber(1),LingoNumber(1),_movieScript.gLOprops.size.loch,_movieScript.gLOprops.size.locv),LingoNumber(2))
        _movieScript.lvleditdraw(LingoGlobal.rect(LingoNumber(1),LingoNumber(1),_movieScript.gLOprops.size.loch,_movieScript.gLOprops.size.locv),LingoNumber(3))
        _movieScript.drawshortcutsimg(LingoGlobal.rect(LingoNumber(1),LingoNumber(1),_movieScript.gLOprops.size.loch,_movieScript.gLOprops.size.locv),LingoNumber(16))
        gdirectionkeys = LingoList(LingoNumber(0),LingoNumber(0),LingoNumber(0),LingoNumber(0))        _global.sprite(LingoNumber(212)).blend = LingoNumber(30)        _global.sprite(LingoNumber(213)).blend = LingoNumber(40)        _global.sprite(LingoNumber(214)).blend = LingoNumber(50)        _global.sprite(LingoNumber(215)).blend = LingoNumber(60)        _global.sprite(LingoNumber(216)).blend = LingoNumber(80)        _global.sprite(LingoNumber(217)).blend = LingoNumber(100)        l = LingoPropertyList(n=LingoNumber(0),m1=LingoNumber(0),m2=LingoNumber(0),w=LingoNumber(0),a=LingoNumber(0),s=LingoNumber(0),d=LingoNumber(0),e=LingoNumber(0),r=LingoNumber(0),f=LingoNumber(0))        _movieScript.gEEprops.lastkeys = l.duplicate()        _movieScript.gEEprops.keys = l.duplicate()        _global.script("effectsEditor").updateeffectsmenu(LingoGlobal.point(LingoNumber(0),LingoNumber(0)))
        _global.script("effectsEditor").updateeffectsl(LingoNumber(0))
        _global.script("effectsEditor").initmode("createNew")
        _global.script("propEditor").renderpropsimage()
        _global.script("effectsEditor").drawefmtrx(_movieScript.gEEprops.editeffect)
        _global.member("Drought Reserve text").text = ""                return None            