from Drizzle.Runtime import *## Behavior script: tileEditorStart#class tileEditorStart(LingoBehaviorScript):     def __init__(self):         super().__init__()            def exitframe(self):         l = None        q = None        _global._movie.exitlock = LingoGlobal.TRUE        _global.member("tileMenu").alignment = left        _global.member("TEimg1").image = _global.image(LingoGlobal.op_mul(LingoNumber(52),LingoNumber(16)),LingoGlobal.op_mul(LingoNumber(40),LingoNumber(16)),LingoNumber(16))        _global.member("TEimg2").image = _global.image(LingoGlobal.op_mul(LingoNumber(52),LingoNumber(16)),LingoGlobal.op_mul(LingoNumber(40),LingoNumber(16)),LingoNumber(16))        _global.member("TEimg3").image = _global.image(LingoGlobal.op_mul(LingoNumber(52),LingoNumber(16)),LingoGlobal.op_mul(LingoNumber(40),LingoNumber(16)),LingoNumber(16))        _global.member("levelEditImage1").image = _global.image(LingoGlobal.op_mul(LingoNumber(52),LingoNumber(16)),LingoGlobal.op_mul(LingoNumber(40),LingoNumber(16)),LingoNumber(16))        _global.member("levelEditImage2").image = _global.image(LingoGlobal.op_mul(LingoNumber(52),LingoNumber(16)),LingoGlobal.op_mul(LingoNumber(40),LingoNumber(16)),LingoNumber(16))        _global.member("levelEditImage3").image = _global.image(LingoGlobal.op_mul(LingoNumber(52),LingoNumber(16)),LingoGlobal.op_mul(LingoNumber(40),LingoNumber(16)),LingoNumber(16))        _global.member("levelEditImageShortCuts").image = _global.image(LingoGlobal.op_mul(LingoNumber(52),LingoNumber(16)),LingoGlobal.op_mul(LingoNumber(40),LingoNumber(16)),LingoNumber(16))        _movieScript.tedraw(LingoGlobal.rect(LingoNumber(1),LingoNumber(1),_movieScript.gLOprops.size.loch,_movieScript.gLOprops.size.locv),LingoNumber(1))
        _movieScript.tedraw(LingoGlobal.rect(LingoNumber(1),LingoNumber(1),_movieScript.gLOprops.size.loch,_movieScript.gLOprops.size.locv),LingoNumber(2))
        _movieScript.tedraw(LingoGlobal.rect(LingoNumber(1),LingoNumber(1),_movieScript.gLOprops.size.loch,_movieScript.gLOprops.size.locv),LingoNumber(3))
        _movieScript.lvleditdraw(LingoGlobal.rect(LingoNumber(1),LingoNumber(1),_movieScript.gLOprops.size.loch,_movieScript.gLOprops.size.locv),LingoNumber(1))
        _movieScript.lvleditdraw(LingoGlobal.rect(LingoNumber(1),LingoNumber(1),_movieScript.gLOprops.size.loch,_movieScript.gLOprops.size.locv),LingoNumber(2))
        _movieScript.lvleditdraw(LingoGlobal.rect(LingoNumber(1),LingoNumber(1),_movieScript.gLOprops.size.loch,_movieScript.gLOprops.size.locv),LingoNumber(3))
        _movieScript.drawshortcutsimg(LingoGlobal.rect(LingoNumber(1),LingoNumber(1),_movieScript.gLOprops.size.loch,_movieScript.gLOprops.size.locv),LingoNumber(16))
        _movieScript.gDirectionKeys = LingoList(LingoNumber(0),LingoNumber(0),LingoNumber(0),LingoNumber(0))        _global.sprite(LingoNumber(1)).blend = LingoNumber(10)        _global.sprite(LingoNumber(2)).blend = LingoNumber(10)        _global.sprite(LingoNumber(3)).blend = LingoNumber(60)        _global.sprite(LingoNumber(4)).blend = LingoNumber(10)        _global.sprite(LingoNumber(5)).blend = LingoNumber(70)        _global.sprite(LingoNumber(6)).blend = LingoNumber(100)        _global.sprite(LingoNumber(8)).blend = LingoNumber(80)        _global.sprite(LingoNumber(8)).visibility = LingoNumber(0)        _global.script("tileEditor").changelayer()
        _global.member("default material").text = LingoGlobal.concat_space("Default material:",_movieScript.gTEprops.defaultmaterial,"(Press 'E' to change)")        _global.sprite(LingoNumber(19)).visibility = LingoNumber(1)        l = LingoPropertyList(dict(l = LingoNumber(0),m1 = LingoNumber(0),m2 = LingoNumber(0),w = LingoNumber(0),a = LingoNumber(0),s = LingoNumber(0),d = LingoNumber(0),c = LingoNumber(0),q = LingoNumber(0)))        _movieScript.gTEprops.lastkeys = l.duplicate()        _movieScript.gTEprops.keys = l.duplicate()        _global.script("tileEditor").updatetilemenu(LingoGlobal.point(LingoNumber(0),LingoNumber(0)))
        _movieScript.gTEprops.tmsavposl = LingoList()        for tmp_q in LingoGlobal.pyrange(LingoNumber(1), _movieScript.gTiles.count):             q = tmp_q            _movieScript.gTEprops.tmsavposl.add(LingoNumber(1))
            tmp_q = q                    _global.member("Drought Reserve text").text = ""                return None            