from Drizzle.Runtime import *## Behavior script: effectsEditorStart#class effectsEditorStart(LingoBehaviorScript):     def __init__(self):         super().__init__()            def exitframe(self):         spr = None        q = None        c = None        gdirectionkeys = None        l = None        self._global._movie.exitlock = LingoGlobal.TRUE        self._global.sprite(LingoNumber(243)).color = self._global.color(LingoNumber(255),LingoNumber(255),LingoNumber(255))        self._global.member("effectsMatrix").image = self._global.image(LingoNumber(52),LingoNumber(40),LingoNumber(32))        self._global.sprite(LingoNumber(212)).blend = LingoNumber(30)        self._global.sprite(LingoNumber(213)).blend = LingoNumber(50)        self._global.sprite(LingoNumber(214)).blend = LingoNumber(70)        self._global.sprite(LingoNumber(215)).blend = LingoNumber(100)        tmp_spr=int(LingoNumber(3))        while tmp_spr < LingoNumber(9):             spr = LingoNumber(tmp_spr)            self._global.sprite(spr).rect = LingoGlobal.rect(LingoNumber(16),LingoNumber(16),LingoGlobal.op_mul(LingoNumber(53),LingoNumber(16)),LingoGlobal.op_mul(LingoNumber(41),LingoNumber(16)))            tmp_spr = int(spr)            tmp_spr += 1                    tmp_q=int(LingoNumber(1))        while tmp_q < self._movieScript.gLOprops.size.loch:             q = LingoNumber(tmp_q)            tmp_c=int(LingoNumber(1))            while tmp_c < self._movieScript.gLOprops.size.locv:                 c = LingoNumber(tmp_c)                self._global.member("effectsMatrix").image.setpixel(LingoGlobal.op_sub(q,LingoNumber(1)),LingoGlobal.op_sub(c,LingoNumber(1)),self._global.color(LingoNumber(0),LingoNumber(0),LingoNumber(0)))
                tmp_c = int(c)                tmp_c += 1                            tmp_q = int(q)            tmp_q += 1                    self._global.member("TEimg1").image = self._global.image(LingoGlobal.op_mul(LingoNumber(52),LingoNumber(16)),LingoGlobal.op_mul(LingoNumber(40),LingoNumber(16)),LingoNumber(16))        self._global.member("TEimg2").image = self._global.image(LingoGlobal.op_mul(LingoNumber(52),LingoNumber(16)),LingoGlobal.op_mul(LingoNumber(40),LingoNumber(16)),LingoNumber(16))        self._global.member("TEimg3").image = self._global.image(LingoGlobal.op_mul(LingoNumber(52),LingoNumber(16)),LingoGlobal.op_mul(LingoNumber(40),LingoNumber(16)),LingoNumber(16))        self._global.member("levelEditImage1").image = self._global.image(LingoGlobal.op_mul(LingoNumber(52),LingoNumber(16)),LingoGlobal.op_mul(LingoNumber(40),LingoNumber(16)),LingoNumber(16))        self._global.member("levelEditImage2").image = self._global.image(LingoGlobal.op_mul(LingoNumber(52),LingoNumber(16)),LingoGlobal.op_mul(LingoNumber(40),LingoNumber(16)),LingoNumber(16))        self._global.member("levelEditImage3").image = self._global.image(LingoGlobal.op_mul(LingoNumber(52),LingoNumber(16)),LingoGlobal.op_mul(LingoNumber(40),LingoNumber(16)),LingoNumber(16))        self._global.member("levelEditImageShortCuts").image = self._global.image(LingoGlobal.op_mul(LingoNumber(52),LingoNumber(16)),LingoGlobal.op_mul(LingoNumber(40),LingoNumber(16)),LingoNumber(16))        self._movieScript.tedraw(LingoGlobal.rect(LingoNumber(1),LingoNumber(1),self._movieScript.gLOprops.size.loch,self._movieScript.gLOprops.size.locv),LingoNumber(1))
        self._movieScript.tedraw(LingoGlobal.rect(LingoNumber(1),LingoNumber(1),self._movieScript.gLOprops.size.loch,self._movieScript.gLOprops.size.locv),LingoNumber(2))
        self._movieScript.tedraw(LingoGlobal.rect(LingoNumber(1),LingoNumber(1),self._movieScript.gLOprops.size.loch,self._movieScript.gLOprops.size.locv),LingoNumber(3))
        self._movieScript.lvleditdraw(LingoGlobal.rect(LingoNumber(1),LingoNumber(1),self._movieScript.gLOprops.size.loch,self._movieScript.gLOprops.size.locv),LingoNumber(1))
        self._movieScript.lvleditdraw(LingoGlobal.rect(LingoNumber(1),LingoNumber(1),self._movieScript.gLOprops.size.loch,self._movieScript.gLOprops.size.locv),LingoNumber(2))
        self._movieScript.lvleditdraw(LingoGlobal.rect(LingoNumber(1),LingoNumber(1),self._movieScript.gLOprops.size.loch,self._movieScript.gLOprops.size.locv),LingoNumber(3))
        self._movieScript.drawshortcutsimg(LingoGlobal.rect(LingoNumber(1),LingoNumber(1),self._movieScript.gLOprops.size.loch,self._movieScript.gLOprops.size.locv),LingoNumber(16))
        gdirectionkeys = LingoList(LingoNumber(0),LingoNumber(0),LingoNumber(0),LingoNumber(0))        self._global.sprite(LingoNumber(212)).blend = LingoNumber(30)        self._global.sprite(LingoNumber(213)).blend = LingoNumber(40)        self._global.sprite(LingoNumber(214)).blend = LingoNumber(50)        self._global.sprite(LingoNumber(215)).blend = LingoNumber(60)        self._global.sprite(LingoNumber(216)).blend = LingoNumber(80)        self._global.sprite(LingoNumber(217)).blend = LingoNumber(100)        l = LingoPropertyList(LingoSymbol("n"), LingoNumber(0),LingoSymbol("m1"), LingoNumber(0),LingoSymbol("m2"), LingoNumber(0),LingoSymbol("w"), LingoNumber(0),LingoSymbol("a"), LingoNumber(0),LingoSymbol("s"), LingoNumber(0),LingoSymbol("d"), LingoNumber(0),LingoSymbol("e"), LingoNumber(0),LingoSymbol("r"), LingoNumber(0),LingoSymbol("f"), LingoNumber(0))        self._movieScript.gEEprops.lastkeys = l.duplicate()        self._movieScript.gEEprops.keys = l.duplicate()        self._global.script("effectsEditor").updateeffectsmenu(LingoGlobal.point(LingoNumber(0),LingoNumber(0)))
        self._global.script("effectsEditor").updateeffectsl(LingoNumber(0))
        self._global.script("effectsEditor").initmode("createNew")
        self._global.script("propEditor").renderpropsimage()
        self._global.script("effectsEditor").drawefmtrx(self._movieScript.gEEprops.editeffect)
        self._global.member("Drought Reserve text").text = ""                return None            